### 100 NumPy Exercices

This notebook have the solution of the 100 exercises found in this [repo](https://github.com/rougier/numpy-100).

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
np.show_config()

2.2.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.28
Compilers:
  c:
    commands: cc
    linker: ld.bfd


### 3. Create a null vector of size 10 (★☆☆)

In [8]:
a = np.zeros(10)

print(a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array (★☆☆)

In [12]:
a = np.arange(10)

print(f"{a.size * a.itemsize} bytes")
print(f"{a.nbytes} bytes")

80 bytes
80 bytes


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
a = np.zeros(10)
a[4] = 1

print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
a = np.arange(10, 50)

print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last) (★☆☆)

In [53]:
a = np.arange(10)

print(f"original: {a}")
print(f"reversed: {a[::-1]}")

original: [0 1 2 3 4 5 6 7 8 9]
reversed: [9 8 7 6 5 4 3 2 1 0]


### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
a = np.arange(9).reshape((3, 3))

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
a = np.array([1, 2, 0, 0, 4, 0])
b = np.arange(a.shape[0])

print(b[a != 0])

[0 1 4]


### 11. Create a 3x3 identity matrix (★☆☆)

In [54]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values (★☆☆)

In [55]:
a = np.random.random((3, 3, 3))

print(a)

[[[0.75858924 0.71851764 0.30952028]
  [0.5435556  0.17699935 0.27765082]
  [0.29328505 0.09399364 0.63321336]]

 [[0.30390256 0.1998141  0.30238139]
  [0.41904504 0.04915405 0.0837261 ]
  [0.87775169 0.82387929 0.80609366]]

 [[0.895364   0.23472688 0.51467553]
  [0.64110152 0.04628508 0.54022758]
  [0.1717011  0.14970015 0.2849381 ]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [57]:
a = np.random.random((10, 10))

print(f"{a}\n")
print(f"minimum: {np.min(a)}")
print(f"maximum: {np.max(a)}")

[[0.93813774 0.11022986 0.2134565  0.09404772 0.82704258 0.0975873
  0.99676359 0.22872284 0.84176375 0.96618455]
 [0.17202827 0.08115642 0.64422404 0.47763749 0.68115577 0.71664751
  0.00249261 0.65842331 0.59251586 0.64257583]
 [0.38486635 0.53835995 0.74282267 0.00511278 0.01929775 0.52733108
  0.45853251 0.36569949 0.07497058 0.3506049 ]
 [0.16704151 0.05034077 0.89220474 0.68859035 0.90667026 0.8968267
  0.46575004 0.22250624 0.87603738 0.17644277]
 [0.74428247 0.42432379 0.52081217 0.49873651 0.8332508  0.87477777
  0.72546784 0.79038975 0.44502655 0.92735699]
 [0.38901167 0.88145135 0.82287826 0.97978399 0.53894673 0.27863293
  0.45502249 0.92830683 0.15444166 0.37953369]
 [0.04773253 0.64766569 0.38798412 0.27827211 0.13056046 0.38848077
  0.56893703 0.90766409 0.61975329 0.48515759]
 [0.91968157 0.36152147 0.66636817 0.98366402 0.37803048 0.02365796
  0.47481214 0.26747213 0.78528189 0.83332056]
 [0.68290298 0.12669888 0.50468771 0.91060612 0.8168171  0.26324302
  0.54098362 0

### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
a = np.random.random(30)

print(f"{a}\n")
print(f"mean: {np.mean(a)}")

[0.28383258 0.02436377 0.10696113 0.40728538 0.30193637 0.6267981
 0.50796654 0.10547277 0.22447216 0.80668263 0.44359889 0.65128259
 0.91206515 0.50641415 0.20085391 0.2690402  0.20742249 0.06798157
 0.6268252  0.95990892 0.67110989 0.67934184 0.36669461 0.1271358
 0.67291765 0.19385722 0.94618757 0.17110449 0.26565205 0.69706865]

mean: 0.43440780781861077


### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [78]:
def border_matrix(m: int, n: int) -> np.ndarray:
    a = np.zeros((m, n), dtype = np.int32)

    a[0::m - 1, :] = 1
    a[:, 0::m - 1] = 1
    
    return a

print(border_matrix(5, 5))

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
