## Understanding Data Types in Python

In this chapter we will learn about the data types and how it is used inside `numpy`.

### Creating Arrays from Python Lists

In this section we will undestanding what is arrays in `numpy` and how to create them.

First of all, we have to import `numpy`:

In [18]:
import numpy as np

Now we can create an array from a python list:

In [19]:
array_1 = np.array([3.14, 4, 3, 2])

print(array_1)

[3.14 4.   3.   2.  ]


And we can explicitly specify the array type:

In [20]:
array_2 = np.array(["hello", ",", "world"], dtype = np.str_)

print(array_2)

['hello' ',' 'world']


We can create a n-dimensional array with numpy:

In [21]:
array_3 = np.array([range(0, 4) for i in range(1, 4)])

print(array_3)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


### Creating Arrays from Scratch

Now we will create numpy arrays from scratch.

For a given length array filled with zeros:

In [22]:
array_4 = np.zeros(20, dtype = int)

print(array_4)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


For an array filled with ones

In [23]:
array_5 = np.zeros((3, 4), dtype = "float128")

print(array_5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


For an array filled with given value:

In [24]:
from random import randint

class opa:
    def __init__(self, name):
        self.name = name
    
    def __repr__(self):
        return f"opa: {self.name}_{randint(1, 100)}"

array_6 = np.full((3, 4), opa("some"))

print(array_6)

[[opa: some_21 opa: some_52 opa: some_5 opa: some_75]
 [opa: some_96 opa: some_15 opa: some_63 opa: some_33]
 [opa: some_70 opa: some_93 opa: some_90 opa: some_61]]


For an array from range:

In [25]:
array_7 = np.arange(0, 0.11, 0.1)

print(array_7)

[0.  0.1]


For an array with k values uniformly distributed inside interval $[a, b]$:

In [26]:
array_8 = np.linspace(0, 1, 40)

print(array_8)

[0.         0.02564103 0.05128205 0.07692308 0.1025641  0.12820513
 0.15384615 0.17948718 0.20512821 0.23076923 0.25641026 0.28205128
 0.30769231 0.33333333 0.35897436 0.38461538 0.41025641 0.43589744
 0.46153846 0.48717949 0.51282051 0.53846154 0.56410256 0.58974359
 0.61538462 0.64102564 0.66666667 0.69230769 0.71794872 0.74358974
 0.76923077 0.79487179 0.82051282 0.84615385 0.87179487 0.8974359
 0.92307692 0.94871795 0.97435897 1.        ]


For an array with pseudorandom numbers:

In [27]:
array_9 = np.random.random((1, 1, 1, 2))

print(array_9)

[[[[0.87032076 0.33200128]]]]


For an array with pseudorandom numbers with mean 0 and stardar deviation 1:

In [28]:
array_10 = np.random.normal(0, 1, 1000000)

m = np.mean(array_10)
s = np.std(array_10)

# print(array_10)
print(abs(0.0 - m))
print(abs(1.0 - s))

0.00048409565144285423
0.0008994842111167412


For an array with pseudorandom integers in interval $[0, 19]$:

In [29]:
array_11 = np.random.randint(-33, 45, 50)

print(array_11)

[ 17  23  17 -20 -28  43  24 -19  -4  -8 -12  12  40  12 -25 -19  40 -15
  -6  33  28  31  15 -10  28  19  42  11   0   6  41  -9   8   9  17  42
  11  41  17   4   2 -30  28  25  42  25  42 -14   5  42]


For a 4x4 identity matrix:

In [30]:
array_12 = np.eye(4)

print(array_12)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


For a empty array (with trash in elements):

In [31]:
array_13 = np.empty(10)

print(array_13)

[4.64437592e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 6.91112809e-310 8.69891861e-043 2.14338399e+184 5.02677779e-091
 1.72171538e+184 6.91117137e-310]


### NumPy Standard Data Types

The numpy arrays contain values of single type, based on `C` types:

In [32]:
array_14 = np.zeros(10, dtype="uint32")

print(array_14)

[0 0 0 0 0 0 0 0 0 0]


are the same that:

In [33]:
array_15 = np.zeros(10, dtype = np.uint32)

print(array_15)

[0 0 0 0 0 0 0 0 0 0]


For more details, access the numpy documentation [NumPy Documentation](https://numpy.org/)