## Understanding Data Types in Python

In this chapter we will learn about the data types and how it is used inside `numpy`.

### Creating Arrays from Python Lists

In this section we will undestanding what is arrays in `numpy` and how to create them.

First of all, we have to import `numpy`:

In [18]:
import numpy as np

Now we can create an array from a python list:

In [19]:
np.array([3.14, 4, 3, 2])

array([3.14, 4.  , 3.  , 2.  ])

And we can explicitly specify the array type:

In [20]:
np.array(["hello", ",", "world"], dtype = np.str_)

array(['hello', ',', 'world'], dtype='<U5')

We can create a n-dimensional array with numpy:

In [21]:
np.array([range(0, 4) for i in range(1, 4)])

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

### Creating Arrays from Scratch

Now we will create numpy arrays from scratch.

For a given length array filled with zeros:

In [22]:
np.zeros(20, dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

For an array filled with ones

In [23]:
np.zeros((3, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

For an array filled with given value:

In [24]:
np.full((3, 4), "sheesh")

array([['sheesh', 'sheesh', 'sheesh', 'sheesh'],
       ['sheesh', 'sheesh', 'sheesh', 'sheesh'],
       ['sheesh', 'sheesh', 'sheesh', 'sheesh']], dtype='<U6')

For an array from range:

In [25]:
np.arange(1, 23, 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

For an array with k values uniformly distributed inside interval $[a, b]$:

In [26]:
np.linspace(0, 1, 13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

For an array with pseudorandom numbers:

In [27]:
np.random.random((3, 4))

array([[0.34723917, 0.95269534, 0.51950751, 0.72126183],
       [0.4718354 , 0.51149685, 0.04988228, 0.44480511],
       [0.22063632, 0.1162762 , 0.15942421, 0.8481165 ]])

For an array with pseudorandom numbers with mean 0 and stardar deviation 1:

In [28]:
np.random.normal(0, 1, (2, 2))

array([[ 1.91436025, -1.17626262],
       [ 0.98525476,  0.36368604]])

For an array with pseudorandom integers in interval $[0, 19]$:

In [29]:
np.random.randint(0, 19, 5)

array([17,  3,  1,  6, 15])

For a 4x4 identity matrix:

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

For a empty array (with trash in elements):

In [31]:
np.empty(10)

array([4.65827477e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.90815730e-310, 3.56852058e-057, 4.99026976e+174, 7.78695447e-091,
       1.51981018e-051, 6.90820404e-310])

### NumPy Standard Data Types

The numpy arrays contain values of single type, based on `C` types:

In [32]:
np.zeros(10, dtype="uint32")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

are the same that:

In [33]:
np.zeros(10, dtype = np.uint32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

For more details, access the numpy documentation [NumPy Documentation](https://numpy.org/)