## The Basics of NumPy Arrays

We will learn how to manipulate arrays in numpy. There is some categories of array operations:

- ***Atributes of arrays***
    - Get the size, shape, memory consumption, and data type of arrays
- ***Indexing of arrays***
    - Get and set elements of array by index
- ***Slicing of arrays***
    - Get subarrays (slices) of arrays
- ***Reshaping of arrays***
    - Change the shape of array
- ***Joining and splitting of arrays***
    - Join multiple arrays in an array and split an array in multiple arrays

### NumPy Array Attributes

Each array has some attributes:

- `ndim`: the number of dimensions
- `shape`: the size of each dimension
- `size`: the total size of array
- `dtype`: the type of each element

Below we have some examples:

In [2]:
import numpy as np

def show(a, s):
    padding = "    "

    print(f"array {s}:")
    print(f"{padding}ndim:  {a.ndim}")
    print(f"{padding}shape: {a.shape}")
    print(f"{padding}size:  {a.size}")
    print(f"{padding}dtype: {a.dtype}\n")

rng = np.random.default_rng(seed = 1731)

a1 = rng.integers(1, 100, size = 5)
a2 = rng.integers(1, 100, size = (2, 3))
a3 = rng.integers(1, 100, size = (2, 2, 3))

show(a1, "a1")
show(a2, "a2")
show(a3, "a3")

array a1:
    ndim:  1
    shape: (5,)
    size:  5
    dtype: int64

array a2:
    ndim:  2
    shape: (2, 3)
    size:  6
    dtype: int64

array a3:
    ndim:  3
    shape: (2, 2, 3)
    size:  12
    dtype: int64



### Array Indexing: Accessing Single Elements

Indexing numpy arrays are a quite like indexing python lists. For 1-dimensional arrays we can access elements by indexing from 0, like python lists. For n-dimensional arrays we can access the elements by indexing with tuples. The indices can be negative, inside the limits of array shape:

In [3]:
a4 = np.random.random(5)

print(f"array[3]: {a4[3]}")
print(f"array:    {a4}")

array[3]: 0.4579025179741746
array:    [0.64334856 0.86606591 0.86294714 0.45790252 0.97962745]


In [4]:
a5 = np.random.random((3, 5))

print(f"array[1, 3]: {a5[1, 3]}")
print(f"array:       {a5}")

array[1, 3]: 0.823593394777425
array:       [[0.95557523 0.79996477 0.86883878 0.78886242 0.43722498]
 [0.57542341 0.01458253 0.08294641 0.82359339 0.56639378]
 [0.65451407 0.48355433 0.28935969 0.83420428 0.27029151]]


You can also modify some element of array:

In [5]:
a6 = np.random.random((5, 6))

a6[-2, 4] = 0.69696969

print(f"array[-2, 4]: {a6[-2, 4]}")
print(f"array:        {a6}")

array[-2, 4]: 0.69696969
array:        [[0.60435635 0.89830075 0.02494014 0.15187561 0.45058153 0.62162825]
 [0.2538858  0.19201505 0.67162812 0.56846515 0.72533532 0.78118706]
 [0.69896275 0.86582748 0.72200263 0.88633267 0.57593745 0.86028831]
 [0.42160123 0.17644462 0.87042408 0.79512286 0.69696969 0.94165777]
 [0.96262045 0.91463397 0.82083076 0.09821395 0.34281215 0.39272947]]


But remember, numpy array have fixed types. Thus, values passed for array elements will be converted to array type (if possible):

In [6]:
a7 = np.array([1, 3, 5, 6, 8], dtype = int)

a7[3] = 1.69696969

print(f"array[3]: {a7[3]}")
print(f"array:    {a7}")

array[3]: 1
array:    [1 3 5 1 8]


### Array Slicing: Accessing Subarrays

Numpy arrays can sliced like python lists whit slices like `array[a:b:k]`.

#### One-Dimensional Subarrays

Here are how slice in 1-D arrays:

In [7]:
a8 = np.array([2, 5, 3, -7, -2, 9, -6])

print(f"a8 = {a8}")
print(f"a8[:] = {a8[:]}")
print(f"a8[:5] = {a8[:5]}")
print(f"a8[2:] = {a8[2:]}")
print(f"a8[2:5] = {a8[2:5]}")
print(f"a8[2:5:2] = {a8[2:5:2]}")
print(f"a8[::2] = {a8[::2]}")
print(f"a8[1::3] = {a8[1::3]}")

a8 = [ 2  5  3 -7 -2  9 -6]
a8[:] = [ 2  5  3 -7 -2  9 -6]
a8[:5] = [ 2  5  3 -7 -2]
a8[2:] = [ 3 -7 -2  9 -6]
a8[2:5] = [ 3 -7 -2]
a8[2:5:2] = [ 3 -2]
a8[::2] = [ 2  3 -2 -6]
a8[1::3] = [ 5 -2]


When step is negative, the start and end of slice are swapped `array[b:a:k]`:

In [8]:
a9 = np.array([2, 5, 3, -7, -2, 9, -6])

print(f"a9[::-1] = {a9[::-1]}")
print(f"a9[:5:-2] = {a9[:5:-2]}")
print(f"a9[2::-1] = {a9[2::-1]}")
print(f"a9[2:5:-2] = {a9[2:5:-2]}")

a9[::-1] = [-6  9 -2 -7  3  5  2]
a9[:5:-2] = [-6]
a9[2::-1] = [3 5 2]
a9[2:5:-2] = []


#### Multidimensional Subarrays

With multidimensional arrays we can do the same, but with each slice separated by comma:

In [9]:
a10 = np.random.random((4, 5))

print(f"{a10}\n")
print(f"{a10[1:3, ::2]}")

[[0.78355497 0.46642727 0.30737269 0.94773739 0.05134401]
 [0.0369701  0.41073016 0.47439989 0.25708179 0.96245508]
 [0.88755064 0.81103915 0.24614988 0.63685676 0.64149702]
 [0.62697936 0.27661161 0.42342655 0.67555409 0.75880272]]

[[0.0369701  0.47439989 0.96245508]
 [0.88755064 0.24614988 0.64149702]]


With that, we can access single rows or columns (or any axes of `ndarray`). For access the thirty columns of `a10` we can do:

In [10]:
print(f"column[2] = {a10[:, 2]}")

column[2] = [0.30737269 0.47439989 0.24614988 0.42342655]


And to access the first line we can do:

In [11]:
print(f"{a10[0, :]}")

[0.78355497 0.46642727 0.30737269 0.94773739 0.05134401]


#### Subarrays as No-Copy Views

Unlike python lists, numpy arrays slices return *views* and not copies of array data. In other words, slices return by reference and not by value, therefore the elements in slice are the same that in the original array, change the slice elements change the array elements:

In [12]:
a11 = np.random.randint(1, 100, (2, 3))

s = a11[:, 1:]

print(f"{a11}\n")
print(f"{s}\n")

s[0, 1] += 13

print(f"{a11}\n")
print(f"{s}\n")

[[30 41 45]
 [20 48 68]]

[[41 45]
 [48 68]]

[[30 41 58]
 [20 48 68]]

[[41 58]
 [48 68]]



#### Creating Copies of Arrays

For create copies of numpy array slices just use the `.copy()` method:

In [13]:
a12 = np.random.randint(1, 100, (2, 3))

s = a12[:, 1:].copy()

print(f"{a12}\n")
print(f"{s}\n")

s[0, 1] += 13

print(f"{a12}\n")
print(f"{s}\n")

[[80 11 11]
 [33 23 44]]

[[11 11]
 [23 44]]

[[80 11 11]
 [33 23 44]]

[[11 24]
 [23 44]]



### Reshaping of Arrays

If you want to reorganize the elements of the array in other shape, we can use the `.reshape()` method:

In [14]:
a13 = np.random.random((2, 2))

print(a13, end = "\n\n")
print(a13.reshape(1, 4), end = "\n\n")
print(a13.reshape(4, 1), end = "\n\n")

[[0.57470726 0.71342292]
 [0.18606574 0.08955998]]

[[0.57470726 0.71342292 0.18606574 0.08955998]]

[[0.57470726]
 [0.71342292]
 [0.18606574]
 [0.08955998]]



Note that the size of the new shape must be the same of the original shape. Furthermore, the `.reshape()` method return a view of the original array:

In [15]:
a14 = np.random.random((2, 2))

print(a14, end = "\n\n")

sh1 = a14.reshape(1, 4)
sh1[0, 1] += 10

print(a14)

[[0.91977752 0.87334046]
 [0.82286855 0.51840243]]

[[ 0.91977752 10.87334046]
 [ 0.82286855  0.51840243]]


You can change the shape of array assign the array with the returned value of `.reshape()` method:

In [16]:
a15 = np.random.random((2, 2))
print(a15, end = "\n\n")
a15 = a13.reshape(1, 4)
print(a15, end = "\n\n")

[[0.16408143 0.42464445]
 [0.54176935 0.79035051]]

[[0.57470726 0.71342292 0.18606574 0.08955998]]



And it's possible turn a 1-d array in n-d array with the `.reshape()` method:

In [17]:
a16 = np.random.random(12)

print(a16, end = "\n\n")
a16 = a16.reshape(3, 4)
print(a16, end = "\n\n")
a16 = a16.reshape(4, 3)
print(a16, end = "\n\n")

[0.82807672 0.4028885  0.46361425 0.81546601 0.03774524 0.92579824
 0.42612787 0.61984888 0.83274655 0.19027957 0.83314739 0.36410073]

[[0.82807672 0.4028885  0.46361425 0.81546601]
 [0.03774524 0.92579824 0.42612787 0.61984888]
 [0.83274655 0.19027957 0.83314739 0.36410073]]

[[0.82807672 0.4028885  0.46361425]
 [0.81546601 0.03774524 0.92579824]
 [0.42612787 0.61984888 0.83274655]
 [0.19027957 0.83314739 0.36410073]]



For turn a line array in a column array we can use `np.newaxis`:

In [18]:
a17 = np.random.random(5)

print(a17, end = "\n\n")
print(a17[:, np.newaxis], end = "\n\n")
print(a17[np.newaxis, :], end = "\n\n")

[0.54860336 0.60770906 0.37772673 0.2782246  0.05226788]

[[0.54860336]
 [0.60770906]
 [0.37772673]
 [0.2782246 ]
 [0.05226788]]

[[0.54860336 0.60770906 0.37772673 0.2782246  0.05226788]]



### Array Concatenation and Splitting

In this section we will learn how to concatenate and split arrays in numpy.

#### Concatenation of Arrays

We can concatenate multiple array in one array, using the methods `np.concatenate()`, `np.vstack()` and `np.hstack()`:

In [19]:
a18 = np.random.randint(1, 100, 3)
a19 = np.random.randint(1, 100, 2)
a20 = np.random.randint(1, 100, 4)

print(f"a18 =             {a18}")
print(f"a19 =             {a19}")
print(f"a20 =             {a20}")
print(f"[a18, a19] =      {np.concatenate([a18, a19])}")
print(f"[a18, a20, a19] = {np.concatenate([a18, a20, a19])}")

a18 =             [91 51 30]
a19 =             [11 91]
a20 =             [97 10 47 86]
[a18, a19] =      [91 51 30 11 91]
[a18, a20, a19] = [91 51 30 97 10 47 86 11 91]


In [20]:
a21 = np.random.random((2, 3))
a22 = np.random.random(3)
a23 = np.random.random((2, 1))

print(f"a21 = \n{a21}\n")
print(f"a22 = \n{a22}\n")
print(f"a23 = \n{a23}\n")
print(f"[a21, a22] = \n{np.vstack([a21, a22])}\n")
print(f"[a21, a23] = \n{np.hstack([a21, a23])}\n")

a21 = 
[[0.70300477 0.21354016 0.7252355 ]
 [0.2039723  0.1058523  0.63953936]]

a22 = 
[0.28085931 0.93455537 0.70246915]

a23 = 
[[0.22114955]
 [0.46099112]]

[a21, a22] = 
[[0.70300477 0.21354016 0.7252355 ]
 [0.2039723  0.1058523  0.63953936]
 [0.28085931 0.93455537 0.70246915]]

[a21, a23] = 
[[0.70300477 0.21354016 0.7252355  0.22114955]
 [0.2039723  0.1058523  0.63953936 0.46099112]]



#### Splitting of Arrays

For split arrays we can use the `np.split()`, `np.hsplit()` and `np.vsplit()`:

In [21]:
a24 = np.random.random(10)

a25, a26, a27 = np.split(a24, [3, 7])

print(a24, end="\n\n")
print(a25, end="\n\n")
print(a26, end="\n\n")
print(a27, end="\n\n")

[0.64713693 0.02493865 0.69628529 0.7177224  0.6375164  0.62229651
 0.33222002 0.02536718 0.17408306 0.17840802]

[0.64713693 0.02493865 0.69628529]

[0.7177224  0.6375164  0.62229651 0.33222002]

[0.02536718 0.17408306 0.17840802]



In [22]:
a28, a29 = np.split(a24, [4])

print(a28, end = "\n\n")
print(a29, end = "\n\n")

[0.64713693 0.02493865 0.69628529 0.7177224 ]

[0.6375164  0.62229651 0.33222002 0.02536718 0.17408306 0.17840802]



In [25]:
a30 = np.arange(20).reshape(4, 5)

a31, a32 = np.hsplit(a30, [2])
a33, a34 = np.vsplit(a30, [3])

print(a30, end = "\n\n")
print(a31, a32, sep = "\n---\n", end = "\n\n")
print(a33, a34, sep = "\n---\n", end = "\n\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]
---
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---
[[15 16 17 18 19]]

