## Computation on NumPy Arrays: Universal Functions

In this section we will learn about universal functions. These functions are much more fast than stardar python and provides an interface to do the computations very fast with python

### The Slowness of Loops

How we know, python is slow. For example, the code below compute the reciprocals of an array with one million elements and it spend approximately 214 ms for run. 

In [47]:
import numpy as np

def compute_reciprocals(values: np.ndarray) -> np.ndarray:
    output = np.zeros(len(values))

    for i in range(0, len(values)):
        output[i] = 1.0 / values[i]
    
    return output

values = np.random.random(1_000_000)

%timeit compute_reciprocals(values)

214 ms ± 92.8 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


But the same code in C run in 0.504 ms, approximately.

In [48]:
from subprocess import run

comp = [
    "gcc", 
    "../codes/ch_6_code_1.c",
    "-o",
    "../codes/main",
    "-O2",
]

exec = ["./../codes/main"]

run(comp)

%timeit run(exec)

504 μs ± 2.44 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In other words, in this example the python code is 424x more slow than C code. For solve this we can use the NumPy's universal functions (ufuncs).

### Introducing Ufuncs

We can ***vectorize*** the `compute_reciprocals()` function with numpy:

In [49]:
def vectorized_compute_reciprocals(values: np.ndarray) -> np.ndarray:
    return 1.0 / values

%timeit vectorized_compute_reciprocals(values)

1.1 ms ± 53.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


> So, our code go from ~217ms to ~1.1ms like magic!

The vectorizarion is implemented via ufuncs, whose purpose is execute repeated operations on values of arrays. In the last example we saw an operation between a scalar and an array, but we can also operate between two arrays:

In [50]:
np.arange(1, 5) / np.arange(3, 7)

array([0.33333333, 0.5       , 0.6       , 0.66666667])

And the operations can be did with multidimensional arrays:

In [51]:
np.arange(9).reshape(3, 3) ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

### Exploring NumPy’s Ufuncs

Ufuncs exist in two flavors: *unary ufuncs* (unary operation) and *bynary ufuncs* (binary operations). We will see some examples of them.

#### Array Arithmetic

The vectorization able to operate numpy arrays like numbers, with the common operations:

In [52]:
a1 = np.arange(1, 6)

print(f"a1      = {a1}")
print(f"a1 + 3  = {a1 + 3}")
print(f"a1 - 3  = {a1 - 3}")
print(f"a1 * 3  = {a1 * 3}")
print(f"a1 / 3  = {a1 / 3}")
print(f"a1 % 3  = {a1 % 3}")
print(f"a1 ** 3 = {a1 ** 3}")

a1      = [1 2 3 4 5]
a1 + 3  = [4 5 6 7 8]
a1 - 3  = [-2 -1  0  1  2]
a1 * 3  = [ 3  6  9 12 15]
a1 / 3  = [0.33333333 0.66666667 1.         1.33333333 1.66666667]
a1 % 3  = [1 2 0 1 2]
a1 ** 3 = [  1   8  27  64 125]


And numpy have some functions for this operations:

| **Operator** | **Function** | **Description** |
| :-: | :- | :- |
| + | np.add | Addition |
| - | np.subtract | Subtraction |
| - | np.negative | Unary negation |
| * | np.multiply | Multiplication |
| / | np.divide | Division |
| // | np.floor_divide | Floor division |
| ** | np.power | Exponentiation |
| % | np.mod | Modulus |


#### Absolute Value

Numpy also provides an absolute value function `np.absolute()` or `np.abs()`:

In [53]:
a2 = np.array([2, -4, 3, -5, 6])

np.abs(a2) # abs(a2)

array([2, 4, 3, 5, 6])

And it works with complex numbers too:

In [54]:
a3 = np.array([2 + 3j, 1 - 5j])

np.abs(a3) # abs(a2)

array([3.60555128, 5.09901951])

#### Trigonometric Functions

Numpy also provides trigonometric functions like `np.sin()`, `np.cos()` amd `np.tan()`:

In [55]:
angles = np.linspace(0, np.pi, 3)

print(f"angles      = {angles}")
print(f"sin(angles) = {np.sin(angles)}")
print(f"cos(angles) = {np.cos(angles)}")
print(f"tan(angles) = {np.tan(angles)}")

angles      = [0.         1.57079633 3.14159265]
sin(angles) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(angles) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(angles) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


And also other trigonometric functions, as the inverse functions:

In [63]:
angles = np.linspace(0, 1, 3)

print(f"angles      = {angles}")
print(f"arcsin(angles) = {np.arcsin(angles)}")
print(f"arccos(angles) = {np.arccos(angles)}")
print(f"arctan(angles) = {np.arctan(angles)}")

angles      = [0.  0.5 1. ]
arcsin(angles) = [0.         0.52359878 1.57079633]
arccos(angles) = [1.57079633 1.04719755 0.        ]
arctan(angles) = [0.         0.46364761 0.78539816]


#### Exponents and Logarithms

Another common operations are the exponentials and the logarithms:

In [57]:
x = np.array([2, 3, 7])

print("Exponentials\n")
print(f"x =   {x}")
print(f"e^x = {np.exp(x)}")
print(f"2^x = {np.exp2(x)}")
print(f"3^x = {np.pow(3.0, x)}")

print("\nLogarithms\n")
print(f"x        = {x}")
print(f"ln(x)    = {np.log(x)}")
print(f"log2(x)  = {np.log2(x)}")
print(f"log3(x)  = {np.log(x) / np.log(3)}")
print(f"log10(x) = {np.log10(x)}")

Exponentials

x =   [2 3 7]
e^x = [   7.3890561    20.08553692 1096.63315843]
2^x = [  4.   8. 128.]
3^x = [   9.   27. 2187.]

Logarithms

x        = [2 3 7]
ln(x)    = [0.69314718 1.09861229 1.94591015]
log2(x)  = [1.         1.5849625  2.80735492]
log3(x)  = [0.63092975 1.         1.77124375]
log10(x) = [0.30103    0.47712125 0.84509804]


There are also some specialized functions that offers more precision results:

In [58]:
x = np.array([2, 3, 7])

print("Specialized Functions\n")
print(f"x =          {x}")
print(f"exp(x) - 1 = {np.expm1(x)}")
print(f"log(x + 1) = {np.log1p(x)}")

Specialized Functions

x =          [2 3 7]
exp(x) - 1 = [   6.3890561    19.08553692 1095.63315843]
log(x + 1) = [1.09861229 1.38629436 2.07944154]


### Advanced Ufunc Features

Here, we will learning some advanced features of numpy ufuncs.

#### Specifying Output

Much numpy operations have an output return and you can specify the output for the operations:

In [59]:
inp = np.arange(3, dtype = int)
out = np.zeros(3, dtype = int)

np.multiply(inp, 2, out = out)

out

array([0, 2, 4])

For large operations this approach is faster than assing, because assign creates a temporary array and copy it for the output array. But using the approach above the values are computed directly in output array, being more fast.

#### Aggregations

For binary ufuncs we have *aggregations*, auxiliary functions over ufuncs that are applied over result of the ufunc. For example, we can sum all values of an array with the `.reduce()` function of `np.add()` operation:

In [60]:
x = np.arange(1, 10)

print(np.add.reduce(x))

45


Or, if you want to get the partial accumulative values of the sum you can use the function `.accumulate()` from `np.add()`:

In [61]:
x = np.arange(1, 10)

print(np.add.accumulate(x))

[ 1  3  6 10 15 21 28 36 45]


#### Outer Products

Finally, if you want to know the result of all possible pairs of the bynary ufunc, you can use the `.outer()` method of any numpy binary ufunc:

In [62]:
a = np.arange(1, 5)
b = np.arange(3, 7)

print(f"a = {a}")
print(f"b = {b}")
print(f"a x b =\n{np.add.outer(a, b)}")

a = [1 2 3 4]
b = [3 4 5 6]
a x b =
[[ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]
