## Comparisons, Masks, and Boolean Logic

In this chapter we will learn about comparisons, masks and boolean logic in numpy.

### Comparison Operators as Ufuncs

In the other chapter we was introduced for the arithmetic operators, like `+`, `-`, `*` and `/`. Now, we will learn about comparison operators:

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(f"a:      {a}")
print(f"a < 3:  {a < 3}")
print(f"a > 3:  {a > 3}")
print(f"a <= 3: {a <= 3}")
print(f"a >= 3: {a >= 3}")
print(f"a == 3: {a == 3}")
print(f"a != 3: {a != 3}")

a:      [1 2 3 4 5]
a < 3:  [ True  True False False False]
a > 3:  [False False False  True  True]
a <= 3: [ True  True  True False False]
a >= 3: [False False  True  True  True]
a == 3: [False False  True False False]
a != 3: [ True  True False  True  True]


This comparisons also works with multi-dimensional arrays. Moreover, each comparison operator has an equivalent ufunc, as seen below:

| Operator | Equivalent ufunc | Operator | Equivalent ufunc |
| :-: | :- | :-: | :- |
| == | np.equal | != | np.not_equal |
| < | np.less | <= | np.less_equal |
| > | np.greater | >= | np.greater_equal |

### Working with Boolean Arrays

As seen above, the comparison operators returns boolean arrays, and we can use this for perform some operations.

#### Counting Entries

For count the number of `True` values in an arrayn, we can use the `no.count_nonzero()` function:

In [16]:
a = np.arange(1, 13).reshape(3, 4)

print(f"array: \n{a}\n")
print(f"numbers less than 7: {np.count_nonzero(a < 7)}")

array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

numbers less than 7: 6


Another way to do this is using the `np.sum()` function, because `False` is interpreted as `0` and `True` is interpreted as `1` by the function:

In [14]:
print(f"array: \n{a}\n")
print(f"numbers less than 7: {np.sum(a < 7)}")

array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

numbers less than 7: 6


For check whether any or all the values are `True`, we can use the functions `np.any()` and `np.all()`:

In [23]:
print(np.any(a < 7))
print(np.any(a > 12))
print(np.all(a < 12))
print(np.all(a <= 12))

True
False
False
True


These functions have the `axis` argument.

#### Boolean Operators

The comparison operators returns boolean arrays and the numpy implements boolean operators for the boolean arrays:

In [6]:
a = np.arange(1, 6)
b = np.arange(3, 8)

print((a < 3) | (a > 4))
print((a > 2) & (a < 4))
print(~(a == 2))

[ True  True False False  True]
[False False  True False False]
[ True False  True  True  True]


The boolean operators have relatable ufuncs:

| Operator | Equivalent ufunc |
| :-: | :- |
| & | np.bitwise_and |
| \| | np.bitwise_or |
| ^ | np.bitwise_xor |
| ~ | np.bitwise_not |

### Boolean Arrays as Masks

When we create a boolean array, we also create a boolean mask that can be used to get some subset of other array by indexing:

In [13]:
a = np.arange(1, 17).reshape(4, 4)
mask = ((a % 2) == 0)

print(f"array: \n{a}\n")
print(f"even numbers: \n{a[mask]}\n")

array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

even numbers: 
[ 2  4  6  8 10 12 14 16]



In [12]:
a = np.arange(1, 31).reshape(5, 6)
mask = ((a % 3) == 0) | ((a % 5) == 0)

print(f"array: \n{a}\n")
print(f"numbers divided by 3 or 5: \n{a[mask]}\n")

array: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

numbers divided by 3 or 5: 
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30]

